version: "3.8"

services:
  react-app:
    container_name: email_demo_ci_react-app
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
